# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXkQKc7iY1X9lzjP-Fy1U9pVEEuQfRbP
"""

!pip install -q pdfplumber langextract pandas reportlab

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import date

pdf_path = "/content/sample_invoice.pdf"
c = canvas.Canvas(pdf_path, pagesize=A4)
width, height = A4

# Header
c.setFont("Helvetica-Bold", 16)
c.drawString(40, height - 60, "ACME Financial Services")
c.setFont("Helvetica", 10)
c.drawString(40, height - 80, "123 Business Rd, Finance City")
c.drawString(40, height - 95, "GSTIN: 27ABCDE1234F2Z5")

# Invoice metadata
c.setFont("Helvetica-Bold", 12)
c.drawString(380, height - 60, "INVOICE")
c.setFont("Helvetica", 10)
c.drawString(380, height - 80, "Invoice No: INV-2025-001")
c.drawString(380, height - 95, f"Date: {date.today().isoformat()}")

# Recipient
c.setFont("Helvetica-Bold", 11)
c.drawString(40, height - 140, "Bill To:")
c.setFont("Helvetica", 10)
c.drawString(40, height - 155, "Ravi & Co.")
c.drawString(40, height - 170, "45 Market Street, Capital City")

# Line items header
y = height - 210
c.setFont("Helvetica-Bold", 10)
c.drawString(40, y, "Description")
c.drawString(300, y, "Qty")
c.drawString(350, y, "Rate")
c.drawString(430, y, "Amount")

# Line items
items = [
    ("Financial consulting - Monthly", 1, 15000.00),
    ("Quarterly audit report", 1, 9000.00),
    ("Transaction fee (processing)", 10, 50.00)
]
y -= 18
c.setFont("Helvetica", 10)
for desc, qty, rate in items:
    amount = qty * rate
    c.drawString(40, y, desc)
    c.drawRightString(320, y, str(qty))
    c.drawRightString(400, y, f"{rate:.2f}")
    c.drawRightString(500, y, f"{amount:.2f}")
    y -= 16

# Totals
subtotal = sum(qty * rate for _, qty, rate in items)
tax = subtotal * 0.18
total = subtotal + tax

y -= 10
c.drawRightString(450, y, "Subtotal:")
c.drawRightString(500, y, f"{subtotal:.2f}")
y -= 16
c.drawRightString(450, y, "GST (18%):")
c.drawRightString(500, y, f"{tax:.2f}")
y -= 16
c.setFont("Helvetica-Bold", 11)
c.drawRightString(450, y, "Total:")
c.drawRightString(500, y, f"{total:.2f}")

c.save()
print("✅ Sample invoice created:", pdf_path)

import pdfplumber

with pdfplumber.open(pdf_path) as pdf:
    text = "\n".join(page.extract_text() for page in pdf.pages)

print("---- Extracted Text ----\n")
print(text)

import os
os.environ["LANGEXTRACT_API_KEY"] = "AIzaSyAvSdvMYtkVvkVp6XjrCny1O-HCsxGWGwA"

import langextract as lx
import textwrap

prompt = textwrap.dedent("""
Extract the following details from the document:
- Vendor Name
- Invoice Number
- Invoice Date
- Subtotal Amount
- Tax Amount
- Total Amount
Return the exact values as seen in the document.
""")

examples = [
    lx.data.ExampleData(
        text="Invoice No: INV-2025-001 Date: 2025-10-31 Vendor: ACME Financial Services Subtotal: 29500.00 GST (18%): 5310.00 Total: 34810.00",
        extractions=[
            lx.data.Extraction(extraction_class="vendor", extraction_text="ACME Financial Services"),
            lx.data.Extraction(extraction_class="invoice_number", extraction_text="INV-2025-001"),
            lx.data.Extraction(extraction_class="date", extraction_text="2025-10-31"),
            lx.data.Extraction(extraction_class="subtotal", extraction_text="29500.00"),
            lx.data.Extraction(extraction_class="tax", extraction_text="5310.00"),
            lx.data.Extraction(extraction_class="total", extraction_text="34810.00"),
        ]
    )
]

result = lx.extract(
    text_or_documents=text,
    prompt_description=prompt,
    examples=examples,
    model_id="gemini-2.5-flash"
)

# Save annotated results for visualization
lx.io.save_annotated_documents([result], output_name="invoice_extractions.jsonl")

print("✅ Extraction done! Saved results to invoice_extractions.jsonl")

html = lx.visualize("/content/test_output/invoice_extractions.jsonl")
display(html)

import pandas as pd

data = {}
for ex in result.extractions:
    data[ex.extraction_class] = ex.extraction_text

df = pd.DataFrame([data])
print("📊 Extracted Data:")
display(df)

df.to_csv("/content/invoice_extracted_data.csv", index=False)
print("✅ Data saved to invoice_extracted_data.csv")

